# Generated by Django 5.2 on 2025-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Authors_with_Templates_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_author',
            new_name='Author',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('book_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Authors', models.ManyToManyField(related_name='Book', to='Books_Authors_with_Templates_app.author')),
            ],
        ),
        migrations.DeleteModel(
            name='add_book',
        ),
    ]
