# Generated by Django 5.0.3 on 2024-04-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='uploaded_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shows_uploaded', to='myapp.user'),
        ),
    ]
