# Generated by Django 5.0.3 on 2024-04-16 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_show_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='uploaded_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shows_uploaded', to='myapp.user'),
        ),
    ]
