# Generated by Django 5.0.3 on 2024-04-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_show_uploaded_by_show_recommended_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='users_who_comment',
            field=models.ManyToManyField(related_name='comments_shows', to='myapp.user'),
        ),
    ]
